# Конфигурация сервисов
services:
    # Конфигурация по умолчанию для сервисов в папке src/
    _defaults:
        autowire: true
        autoconfigure: true
        # public: false

    App\:
        resource: '../src/'
        exclude:
            - '../src/Exception/'
            - '../src/Model/'
            - '../src/DependencyInjection/'
            - '../src/Entity/'
            - '../src/Kernel.php'
   
    # Явно регистрируем логгер как сервис
    Psr\Log\LoggerInterface: '@monolog.logger'

    # Инициализируем JsonSerializer для ReportMessage
    App\Messenger\JsonSerializer:
        class: App\Messenger\JsonSerializer
        arguments:
            - '@logger'

    # Регистрируем сервисы приложения
    App\Interface\TaskTrackerInterface:
        class: App\Service\JiraService
        arguments:
            - '@logger'
            - '%env(JIRA_LINK)%'
            - '%env(JIRA_BASE_URL)%'
            - '%env(JIRA_TOKEN)%'

    # Регистрируем сервисы модуля Report
    App\Modules\Report\Interface\ReportServiceInterface:
        class: App\Modules\Report\Service\PachkaService
        arguments:
            - '@logger'
            - '%env(PACHKA_WEBHOOK)%'

    # Регистрируем сервисы модуля Scheduler
    App\Modules\Scheduler\Interface\RouterInterface:
        class: App\Modules\Scheduler\Service\JiraRouterService
        arguments:
            - '@logger'
            - '@Symfony\Component\Messenger\MessageBusInterface'
            - '%env(JIRA_PROJECT_ID)%'
            - '%env(JIRA_TEST_MODE)%'
            - '%env(JIRA_TEST_TAG)%'
            - '%env(JIRA_AI_TAG)%'
            - '%env(JIRA_AI_BASE_STATUS)%'

    # Регистрируем сервисы модуля Automate
    App\Modules\Automate\Service\AutomateService:
        arguments:
            - '@logger'
            - '@service_container'

    # Регистрируем правила автоматизации
    App\Modules\Automate\Rule\ReportStatusChangedRule:
        public: true

    # Регистрируем контроллеры как публичные сервисы
    App\Modules\Scheduler\Controller\JiraController:
        public: true
        arguments:
            - '@logger'
            - '@App\Modules\Scheduler\Interface\RouterInterface'
            - '@App\Interface\TaskTrackerInterface'
