framework:
    messenger:
        buses:
            default:
                middleware:
                    - App\Messenger\Middleware\LoggerMiddleware
                   
        transports:
            jira_event_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    group.id: '%env(KAFKA_TOPIC_EVENT)%'
                    auto.offset.reset: 'earliest'
                    producer_topic: '%env(KAFKA_TOPIC_EVENT)%'
                    consumer_topics: 
                        - '%env(KAFKA_TOPIC_EVENT)%'
                    retries: '0'
                    message.send.max.retries: '0'

            report_transport:
                dsn: '%env(MESSENGER_TRANSPORT_DSN)%'
                options:
                    metadata.broker.list: '%env(KAFKA_BROKERS)%'
                    group.id: '%env(KAFKA_TOPIC_REPORT)%'
                    auto.offset.reset: 'earliest'
                    producer_topic: '%env(KAFKA_TOPIC_REPORT)%'
                    consumer_topics: 
                        - '%env(KAFKA_TOPIC_REPORT)%'
                    retries: '0'
                    message.send.max.retries: '0'            

        routing:
            'App\Messenger\DTO\AutomateMessage': jira_event_transport
            'App\Messenger\DTO\ReportMessage': report_transport

        serializer:
            default_serializer: messenger.transport.symfony_serializer

